import ROOT
import os
import sys
import math
import datetime
import copy
from systWeights import *

class OutTTreeHandler:
    def __init__(self, fileName):
        now = datetime.datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(current_time, " --- STARTING INITIALIZATION OF TTREEHANDLER ---")
        self.outTreeFile = ROOT.TFile(fileName , "RECREATE")
        print('Creating output file: ', fileName)

        self.trees = []
        for i in range(10):
            self.trees.append(None)
        self.maxSysts = 0
        self.addPDF = True
        self.addQ2 = False
        self.addTopPt = False
        self.addVHF = False
        self.addTTSplit = False
        self.addTopTagging = False
        self.addWTagging = False
        self.addTrigSF = False
        self.nPDF = 0
        self.tree = systWeights()
        self.var_list = []
        
        self.lenjet = 25
        self.lenfatjet = 20

        #SET weights
        self.tree.prepareDefault(True, self.addQ2, self.addPDF, self.addTopPt, self.addVHF, self.addTTSplit)
        self.tree.addSelection("all")
        self.tree.initTreesSysts(self.trees, self.outTreeFile)
        self.tree.setWeightName("w_nominal",1.)
        self.tree.setWeightName("puSF",1.)
        self.tree.setWeightName("puUp",1.)
        self.tree.setWeightName("puDown",1.)
        self.tree.setWeightName("lepSF",1.)
        self.tree.setWeightName("lepUp",1.)
        self.tree.setWeightName("lepDown",1.)
        self.tree.setWeightName("PFSF",1.)
        self.tree.setWeightName("PFUp",1.)
        self.tree.setWeightName("PFDown",1.)
        self.tree.setWeightName("tau_vsjet_SF",1.)
        self.tree.setWeightName("tau_vsjet_Up",1.)
        self.tree.setWeightName("tau_vsjet_Down",1.)
        self.tree.setWeightName("tau_vsele_SF",1.)
        self.tree.setWeightName("tau_vsele_Up",1.)
        self.tree.setWeightName("tau_vsele_Down",1.)
        self.tree.setWeightName("tau_vsmu_SF",1.)
        self.tree.setWeightName("tau_vsmu_Up",1.)
        self.tree.setWeightName("tau_vsmu_Down",1.)
        self.tree.setWeightName("tauSF",1.)
        self.tree.setWeightName("tauUp",1.)
        self.tree.setWeightName("tauDown",1.)
        self.tree.setWeightName("TESSF",1.)
        self.tree.setWeightName("TESUp",1.)
        self.tree.setWeightName("TESDown",1.)
        self.tree.setWeightName("FESSF",1.)
        self.tree.setWeightName("FESUp",1.)
        self.tree.setWeightName("FESDown",1.)
        self.tree.setWeightName("btagSF",1.)
        self.tree.setWeightName("btagUp",1.)
        self.tree.setWeightName("btagDown",1.)
        self.tree.setWeightName("mistagUp",1.)
        self.tree.setWeightName("mistagDown",1.)

        #Init and setup variables
        self.FakeLepton_pt               =   array.array('f', [-999.])
        self.FakeLepton_eta              =   array.array('f', [-999.])
        self.FakeLepton_phi              =   array.array('f', [-999.])
        self.FakeLepton_mass             =   array.array('f', [-999.])
        self.FakeLepton_pdgid            =   array.array('i', [-999])
        self.FakeLepton_pfRelIso04       =   array.array('f', [-999.])
        self.FakeLepton_jetRelIso        =   array.array('f', [-999.])
        self.FakeLepton_miniPFRelIso     =   array.array('f', [-999.])
        self.FakeLepton_tkRelIso         =   array.array('f', [-999.])
        self.FakeLepton_isPrompt         =   array.array('f', [-999.])
        self.FakeLepton_isTight          =   array.array('f', [-999.])
        self.FakeElectron_pt             =   array.array('f', [-999.])
        self.FakeElectron_relIso         =   array.array('f', [-999.])
        self.FakeElectron_eta            =   array.array('f', [-999.])
        self.FakeElectron_phi            =   array.array('f', [-999.])
        self.FakeElectron_mass           =   array.array('f', [-999.])
        self.FakeElectron_pdgid          =   array.array('i', [-999])
        self.FakeElectron_pfRelIso04     =   array.array('f', [-999.])
        self.FakeElectron_isPrompt       =   array.array('f', [-999.])
        self.FakeElectron_WP90           =   array.array('f', [-999.])
        self.FakeMuon_pt                 =   array.array('f', [-999.])
        self.FakeMuon_relIso             =   array.array('f', [-999.])
        self.FakeMuon_eta                =   array.array('f', [-999.])
        self.FakeMuon_phi                =   array.array('f', [-999.])
        self.FakeMuon_mass               =   array.array('f', [-999.])
        self.FakeMuon_pdgid              =   array.array('i', [-999])
        self.FakeMuon_pfRelIso04         =   array.array('f', [-999.])
        self.FakeMuon_isPrompt           =   array.array('f', [-999.])
        self.FakeMuon_TightId            =   array.array('f', [-999.])
        self.FakeTau_pt                  =   array.array('f', [-999.])
        self.FakeTau_isPrompt            =   array.array('f', [-999.])
        self.FakeTau_eta                 =   array.array('f', [-999.])
        self.FakeTau_phi                 =   array.array('f', [-999.])
        self.FakeTau_charge              =   array.array('i', [-999])
        self.FakeTau_mass                =   array.array('f', [-999.])
        self.FakeTau_DeepTauWP           =   array.array('f', [-999.])
        self.Jet_pt                      =   array.array('f', [-999.]*self.lenjet)
        self.Jet_eta                     =   array.array('f', [-999.]*self.lenjet)
        self.Jet_phi                     =   array.array('f', [-999.]*self.lenjet)
        self.FatJet_pt                   =   array.array('f', [-999.]*self.lenfatjet)
        self.FatJet_eta                  =   array.array('f', [-999.]*self.lenfatjet)
        self.FatJet_phi                  =   array.array('f', [-999.]*self.lenfatjet)
        self.FatJet_SDmass               =   array.array('f', [-999.]*self.lenfatjet)
        self.FatJet_SDmass_PUPPI         =   array.array('f', [-999.]*self.lenfatjet)
        self.FatJet_tau21                =   array.array('f', [-999.]*self.lenfatjet)
        self.FatJet_tau32                =   array.array('f', [-999.]*self.lenfatjet)
        self.FatJet_tau43                =   array.array('f', [-999.]*self.lenfatjet)
        self.Jet_number                  =   array.array('f', [-999.])
        self.Jet_numberSeparate          =   array.array('f', [-999.])
        self.FatJet_number               =   array.array('f', [-999.])
        self.FatJet_numberSeparate       =   array.array('f', [-999.])
        self.mT_eleMET                   =   array.array('f', [-999.])
        self.mT_muMET                    =   array.array('f', [-999.])
        self.mT_tauMET                   =   array.array('f', [-999.])
        self.mT_lepMET                   =   array.array('f', [-999.])
        self.mT_leppuppiMET              =   array.array('f', [-999.])
        self.nLeps_LightLeptonsVL        =   array.array('f', [-999.])
        self.nLeps_LightLeptons          =   array.array('f', [-999.])
        self.nLeps_LightLeptonsTight     =   array.array('f', [-999.])
        self.Veto_Electrons              =   array.array('f', [-999.])
        self.Veto_Muons                  =   array.array('f', [-999.])
        self.Veto_TauLeptons             =   array.array('f', [-999.])
        self.Veto_TauZMass               =   array.array('f', [-999.])
        self.HLT_effLumi                 =   array.array('f', [-999.])
        self.MET_pt                      =   array.array('f', [-999.])
        self.MET_phi                     =   array.array('f', [-999.])
        self.puppiMET_pt                 =   array.array('f', [-999.])
        self.puppiMET_phi                =   array.array('f', [-999.])

        self.tree.branchTreesSysts(self.trees, "all", "FakeLepton_pt",            self.outTreeFile, self.FakeLepton_pt)
        self.tree.branchTreesSysts(self.trees, "all", "FakeLepton_isPrompt",      self.outTreeFile, self.FakeLepton_isPrompt)
        self.tree.branchTreesSysts(self.trees, "all", "FakeLepton_eta",           self.outTreeFile, self.FakeLepton_eta)
        self.tree.branchTreesSysts(self.trees, "all", "FakeLepton_phi",           self.outTreeFile, self.FakeLepton_phi)
        self.tree.branchTreesSysts(self.trees, "all", "FakeLepton_mass",          self.outTreeFile, self.FakeLepton_mass)
        self.tree.branchTreesSysts(self.trees, "all", "FakeLepton_pdgid",         self.outTreeFile, self.FakeLepton_pdgid)
        self.tree.branchTreesSysts(self.trees, "all", "FakeLepton_pfRelIso04",    self.outTreeFile, self.FakeLepton_pfRelIso04)
        self.tree.branchTreesSysts(self.trees, "all", "FakeLepton_jetRelIso",     self.outTreeFile, self.FakeLepton_jetRelIso)
        self.tree.branchTreesSysts(self.trees, "all", "FakeLepton_miniPFRelIso",  self.outTreeFile, self.FakeLepton_miniPFRelIso)
        self.tree.branchTreesSysts(self.trees, "all", "FakeLepton_tkRelIso",      self.outTreeFile, self.FakeLepton_tkRelIso)
        self.tree.branchTreesSysts(self.trees, "all", "FakeLepton_isTight",       self.outTreeFile, self.FakeLepton_isTight)
        self.tree.branchTreesSysts(self.trees, "all", "FakeElectron_pt",          self.outTreeFile, self.FakeElectron_pt)
        self.tree.branchTreesSysts(self.trees, "all", "FakeElectron_relIso",      self.outTreeFile, self.FakeElectron_relIso)
        self.tree.branchTreesSysts(self.trees, "all", "FakeElectron_isPrompt",    self.outTreeFile, self.FakeElectron_isPrompt)
        self.tree.branchTreesSysts(self.trees, "all", "FakeElectron_eta",         self.outTreeFile, self.FakeElectron_eta)
        self.tree.branchTreesSysts(self.trees, "all", "FakeElectron_phi",         self.outTreeFile, self.FakeElectron_phi)
        self.tree.branchTreesSysts(self.trees, "all", "FakeElectron_mass",        self.outTreeFile, self.FakeElectron_mass)
        self.tree.branchTreesSysts(self.trees, "all", "FakeElectron_pdgid",       self.outTreeFile, self.FakeElectron_pdgid)
        self.tree.branchTreesSysts(self.trees, "all", "FakeElectron_pfRelIso04",  self.outTreeFile, self.FakeElectron_pfRelIso04)
        self.tree.branchTreesSysts(self.trees, "all", "FakeElectron_WP90",        self.outTreeFile, self.FakeElectron_WP90)
        self.tree.branchTreesSysts(self.trees, "all", "FakeMuon_pt",              self.outTreeFile, self.FakeMuon_pt)
        self.tree.branchTreesSysts(self.trees, "all", "FakeMuon_relIso",          self.outTreeFile, self.FakeMuon_relIso)
        self.tree.branchTreesSysts(self.trees, "all", "FakeMuon_isPrompt",        self.outTreeFile, self.FakeMuon_isPrompt)
        self.tree.branchTreesSysts(self.trees, "all", "FakeMuon_eta",             self.outTreeFile, self.FakeMuon_eta)
        self.tree.branchTreesSysts(self.trees, "all", "FakeMuon_phi",             self.outTreeFile, self.FakeMuon_phi)
        self.tree.branchTreesSysts(self.trees, "all", "FakeMuon_mass",            self.outTreeFile, self.FakeMuon_mass)
        self.tree.branchTreesSysts(self.trees, "all", "FakeMuon_pdgid",           self.outTreeFile, self.FakeMuon_pdgid)
        self.tree.branchTreesSysts(self.trees, "all", "FakeMuon_pfRelIso04",      self.outTreeFile, self.FakeMuon_pfRelIso04)
        self.tree.branchTreesSysts(self.trees, "all", "FakeMuon_TightId",         self.outTreeFile, self.FakeMuon_TightId)
        self.tree.branchTreesSysts(self.trees, "all", "HLT_effLumi",              self.outTreeFile, self.HLT_effLumi)
        self.tree.branchTreesSysts(self.trees, "all", "FakeTau_pt",               self.outTreeFile, self.FakeTau_pt)
        self.tree.branchTreesSysts(self.trees, "all", "FakeTau_isPrompt",         self.outTreeFile, self.FakeTau_isPrompt)
        self.tree.branchTreesSysts(self.trees, "all", "FakeTau_eta",              self.outTreeFile, self.FakeTau_eta)
        self.tree.branchTreesSysts(self.trees, "all", "FakeTau_phi",              self.outTreeFile, self.FakeTau_phi)
        self.tree.branchTreesSysts(self.trees, "all", "FakeTau_mass",             self.outTreeFile, self.FakeTau_mass)
        self.tree.branchTreesSysts(self.trees, "all", "FakeTau_DeepTauWP",        self.outTreeFile, self.FakeTau_DeepTauWP)
        self.tree.branchTreesSysts(self.trees, "all", "Jet_pt",                   self.outTreeFile, self.Jet_pt)
        self.tree.branchTreesSysts(self.trees, "all", "Jet_eta",                  self.outTreeFile, self.Jet_eta)
        self.tree.branchTreesSysts(self.trees, "all", "Jet_phi",                  self.outTreeFile, self.Jet_phi)
        self.tree.branchTreesSysts(self.trees, "all", "Jet_number",               self.outTreeFile, self.Jet_number)
        self.tree.branchTreesSysts(self.trees, "all", "Jet_numberSeparate",       self.outTreeFile, self.Jet_numberSeparate)
        self.tree.branchTreesSysts(self.trees, "all", "FatJet_pt",                self.outTreeFile, self.FatJet_pt)
        self.tree.branchTreesSysts(self.trees, "all", "FatJet_eta",               self.outTreeFile, self.FatJet_eta)
        self.tree.branchTreesSysts(self.trees, "all", "FatJet_phi",               self.outTreeFile, self.FatJet_phi)
        self.tree.branchTreesSysts(self.trees, "all", "FatJet_SDmass",            self.outTreeFile, self.FatJet_SDmass)
        self.tree.branchTreesSysts(self.trees, "all", "FatJet_SDmass_PUPPI",      self.outTreeFile, self.FatJet_SDmass_PUPPI)
        self.tree.branchTreesSysts(self.trees, "all", "FatJet_tau21",             self.outTreeFile, self.FatJet_tau21)
        self.tree.branchTreesSysts(self.trees, "all", "FatJet_tau32",             self.outTreeFile, self.FatJet_tau32)
        self.tree.branchTreesSysts(self.trees, "all", "FatJet_tau43",             self.outTreeFile, self.FatJet_tau43)
        self.tree.branchTreesSysts(self.trees, "all", "FatJet_number",            self.outTreeFile, self.FatJet_number)
        self.tree.branchTreesSysts(self.trees, "all", "FatJet_numberSeparate",    self.outTreeFile, self.FatJet_numberSeparate)
        self.tree.branchTreesSysts(self.trees, "all", "nLeps_LightLeptonsVL",     self.outTreeFile, self.nLeps_LightLeptonsVL)
        self.tree.branchTreesSysts(self.trees, "all", "nLeps_LightLeptons",       self.outTreeFile, self.nLeps_LightLeptons)
        self.tree.branchTreesSysts(self.trees, "all", "nLeps_LightLeptonsTight",  self.outTreeFile, self.nLeps_LightLeptonsTight)
        self.tree.branchTreesSysts(self.trees, "all", "Veto_TauLeptons",          self.outTreeFile, self.Veto_TauLeptons)
        self.tree.branchTreesSysts(self.trees, "all", "Veto_TauZMass",            self.outTreeFile, self.Veto_TauZMass)
        self.tree.branchTreesSysts(self.trees, "all", "MET_pt",                   self.outTreeFile, self.MET_pt)
        self.tree.branchTreesSysts(self.trees, "all", "puppiMET_pt",              self.outTreeFile, self.puppiMET_pt)
        self.tree.branchTreesSysts(self.trees, "all", "puppiMET_phi",             self.outTreeFile, self.puppiMET_phi)
        self.tree.branchTreesSysts(self.trees, "all", "mT_lepMET",                self.outTreeFile, self.mT_lepMET)
        self.tree.branchTreesSysts(self.trees, "all", "mT_leppuppiMET",           self.outTreeFile, self.mT_leppuppiMET)
        self.tree.branchTreesSysts(self.trees, "all", "mT_eleMET",                self.outTreeFile, self.mT_eleMET)
        self.tree.branchTreesSysts(self.trees, "all", "mT_muMET",                 self.outTreeFile, self.mT_muMET)
        self.tree.branchTreesSysts(self.trees, "all", "mT_tauMET",                self.outTreeFile, self.mT_tauMET)
        now = datetime.datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(current_time, " --- ENDED INITIALIZATION OF TTREEHANDLER ---")
        
    def HelloWorld(self):
        print(self.FakeElectron_eta)

    def clearVar(self):
            self.FakeLepton_pt               =   array.array('f', [-999.])
            self.FakeLepton_eta              =   array.array('f', [-999.])
            self.FakeLepton_phi              =   array.array('f', [-999.])
            self.FakeLepton_mass             =   array.array('f', [-999.])
            self.FakeLepton_pdgid            =   array.array('i', [-999])
            self.FakeLepton_pfRelIso04       =   array.array('f', [-999.])
            self.FakeLepton_jetRelIso        =   array.array('f', [-999.])
            self.FakeLepton_miniPFRelIso     =   array.array('f', [-999.])
            self.FakeLepton_tkRelIso         =   array.array('f', [-999.])
            self.FakeLepton_isPrompt         =   array.array('f', [-999.])
            self.FakeLepton_isTight          =   array.array('f', [-999.])
            self.FakeElectron_pt             =   array.array('f', [-999.])
            self.FakeElectron_relIso         =   array.array('f', [-999.])
            self.FakeElectron_eta            =   array.array('f', [-999.])
            self.FakeElectron_phi            =   array.array('f', [-999.])
            self.FakeElectron_mass           =   array.array('f', [-999.])
            self.FakeElectron_pdgid          =   array.array('i', [-999])
            self.FakeElectron_pfRelIso04     =   array.array('f', [-999.])
            self.FakeElectron_isPrompt       =   array.array('f', [-999.])
            self.FakeElectron_WP90           =   array.array('f', [-999.])
            self.FakeMuon_pt                 =   array.array('f', [-999.])
            self.FakeMuon_relIso             =   array.array('f', [-999.])
            self.FakeMuon_eta                =   array.array('f', [-999.])
            self.FakeMuon_phi                =   array.array('f', [-999.])
            self.FakeMuon_mass               =   array.array('f', [-999.])
            self.FakeMuon_pdgid              =   array.array('i', [-999])
            self.FakeMuon_pfRelIso04         =   array.array('f', [-999.])
            self.FakeMuon_isPrompt           =   array.array('f', [-999.])
            self.FakeMuon_TightId            =   array.array('f', [-999.])
            self.FakeTau_pt                  =   array.array('f', [-999.])
            self.FakeTau_isPrompt            =   array.array('f', [-999.])
            self.FakeTau_eta                 =   array.array('f', [-999.])
            self.FakeTau_phi                 =   array.array('f', [-999.])
            self.FakeTau_charge              =   array.array('i', [-999])
            self.FakeTau_mass                =   array.array('f', [-999.])
            self.FakeTau_DeepTauWP           =   array.array('f', [-999.])
            self.Jet_pt                      =   array.array('f', [-999.]*self.lenjet)
            self.Jet_eta                     =   array.array('f', [-999.]*self.lenjet)
            self.Jet_phi                     =   array.array('f', [-999.]*self.lenjet)
            self.FatJet_pt                   =   array.array('f', [-999.]*self.lenfatjet)
            self.FatJet_eta                  =   array.array('f', [-999.]*self.lenfatjet)
            self.FatJet_phi                  =   array.array('f', [-999.]*self.lenfatjet)
            self.FatJet_SDmass               =   array.array('f', [-999.]*self.lenfatjet)
            self.FatJet_SDmass_PUPPI         =   array.array('f', [-999.]*self.lenfatjet)
            self.FatJet_tau21                =   array.array('f', [-999.]*self.lenfatjet)
            self.FatJet_tau32                =   array.array('f', [-999.]*self.lenfatjet)
            self.FatJet_tau43                =   array.array('f', [-999.]*self.lenfatjet)
            self.Jet_number                  =   array.array('f', [-999.])
            self.Jet_numberSeparate          =   array.array('f', [-999.])
            self.FatJet_number               =   array.array('f', [-999.])
            self.FatJet_numberSeparate       =   array.array('f', [-999.])
            self.mT_eleMET                   =   array.array('f', [-999.])
            self.mT_muMET                    =   array.array('f', [-999.])
            self.mT_tauMET                   =   array.array('f', [-999.])
            self.mT_lepMET                   =   array.array('f', [-999.])
            self.mT_leppuppiMET              =   array.array('f', [-999.])
            self.nLeps_LightLeptonsVL        =   array.array('f', [-999.])
            self.nLeps_LightLeptons          =   array.array('f', [-999.])
            self.nLeps_LightLeptonsTight     =   array.array('f', [-999.])
            self.Veto_Electrons              =   array.array('f', [-999.])
            self.Veto_Muons                  =   array.array('f', [-999.])
            self.Veto_TauLeptons             =   array.array('f', [-999.])
            self.Veto_TauZMass               =   array.array('f', [-999.])
            self.HLT_effLumi                 =   array.array('f', [-999.])
            self.MET_pt                      =   array.array('f', [-999.])
            self.MET_phi                     =   array.array('f', [-999.])
            self.puppiMET_pt                 =   array.array('f', [-999.])
            self.puppiMET_phi                =   array.array('f', [-999.])

        


