python submit_condor_old.py -d ZZTo2L2Nu_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d ZZTo4L_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToContinToZZTo4e_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToContinToZZTo2e2mu_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToContinToZZTo2e2tau_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToContinToZZTo4mu_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToContinToZZTo2mu2tau_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToContinToZZTo4tau_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d TT_SemiLep_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d TT_Had_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d TTTo2L2Nu_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d TTGJets_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d TTZToQQ_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d TTZToLLNuNu_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d TTWJetsToQQ_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d TTWJetsToLNu_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d tZq_ll_4f_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d ZG_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WG_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WWto2L2Nu_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToWWToENEN_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToWWToENMN_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToWWToENTN_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToWWToMNEN_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToWWToMNMN_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToWWToMNTN_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToWWToTNEN_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToWWToTNMN_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluToWWToTNTN_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d ST_tW_top_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d ST_tW_antitop_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluHToWWTo2L2Nu_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d GluGluHToTauTau_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d VBFHToWWTo2L2Nu_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d ttHToNonbb_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d VHToNonbb_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WWW_4F_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WWZ_4F_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WZZ_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d ZZZ_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WWG_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WJetsHT70to100_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WJetsHT100to200_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WJetsHT200to400_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WJetsHT400to600_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WJetsHT600to800_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WJetsHT800to1200_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WJetsHT1200to2500_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WJetsHT2500toInf_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d WZ_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d DYJetsToLL_M50_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d DYJetsToLL_M50_UL2016APV_ext  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d VBS_SSWW_cHW_BSM_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d VBS_SSWW_cHW_INT_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d VBS_SSWW_cW_BSM_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d VBS_SSWW_cW_INT_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d VBS_SSWW_cW_cHW_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d DataMuB2_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d DataMuC_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d DataMuD_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d DataMuE_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d DataMuF_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d DataEleB2_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d DataEleC_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d DataEleD_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d DataEleE_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
python submit_condor_old.py -d DataEleF_UL2016APV  -f vUL003/ltau --wpjet VT --wpele VL --wpmu T --reco jl --masscrit --deltaeta
